# Generated by Django 5.1.5 on 2025-01-28 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 28, 10, 50, 50, 111123, tzinfo=datetime.timezone.utc)),
        ),
    ]
