# Generated by Django 5.1.5 on 2025-01-28 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 28, 12, 46, 22, 588264, tzinfo=datetime.timezone.utc)),
        ),
    ]
